### ISSUE TITLE
Building on Ubuntu 14.04 fails because libnvtrc.so can't be found

### ISSUE THREAD

**Issue by oddeirik** [jcuda/jcuda-common#2]
Building the native libraries on Ubuntu 14.04 with the CUDA 7.5 SDK from nVidias own repo (http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/) fails because libnvrtc.so can't be found (referenced as CUDA_nvrtc_LIBRARY by FindCUDA.cmake). It seems this is caused by the libraries being located under <SDK_location>/targets/x86_64-linux/lib and not just lib/x64 (as they are on Windows which I compared against).

I added an additional path suffix to JCudaCommon_CMake.txt and it builds fine. I don't think this should cause any issues for other platforms, but I haven't tested it myself.

Here's a diff of the change done. I was too lazy to create a pull request, sorry :)

```
diff --git a/JCudaCommon_CMake.txt b/JCudaCommon_CMake.txt
index bae7cad..199014a 100644
--- a/JCudaCommon_CMake.txt
+++ b/JCudaCommon_CMake.txt
@@ -26,7 +26,7 @@ if (NOT CUDA_FOUND)
     find_library(CUDA_nvrtc_LIBRARY
         NAMES nvrtc
         HINTS ${CUDA_TOOLKIT_ROOT_DIR}
-        PATH_SUFFIXES /lib/x64)
+        PATH_SUFFIXES /lib/x64 /targets/x86_64-linux/lib)
 endif()

 if (NOT JNI_FOUND)
```

**Comment by jcuda** [comment]
This is basically the same issue as https://github.com/jcuda/jcuda/issues/3 . I already tried to fix it with the `lib/x64` path suffix, but did not receive a direct answer to the fix before the comment https://github.com/jcuda/jcuda/issues/3#issuecomment-218798713 about whether it properly worked on linux as well.

However, I tested your solution, and it works on windows as well, so I assume that this is also solved now.

Thanks for your contribution!
